config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get "/signup", to: "users#new", as: "signup"
  get "/login", to: 'sessions#new', as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"
  resources :users
  resources :events
  put "/events", to: "events#subscribe", as: "subscribe"
  put "/users/:id/:event", to: "events#unsubscribe", as: "unsubscribe"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :date, uniqueness: true, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attending_events, through: :event_attendees, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include SessionsHelper
   include EventsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @current_user = current_user
    @event = Event.new(params_event)
    @event.creator_id = @current_user.id
    @event.save
    if @event.save
      redirect_to event_path(@event.id)
    else
      flash.now[:danger] = "Couldn't save."
      render action: "new"
    end
  end

  def index
    if logged_in?
      @events = Event.all
      events_aging(@events)
      @attending_list = attending?
    else
      flash[:danger] = "Veuillez vous connecter pour accéder à la liste des évènements."
      redirect_to login_path
    end
  end

  def show
    if logged_in?
      @event = Event.find(params[:id])
      @attending_list = attending?
    else
      redirect_to login_path
    end
  end

  def subscribe
    @event = Event.find(params[:event])
    @current_user = current_user
    @event.attendees << @current_user
    flash[:success] = "Tu as bien rejoint l'évènement !!"
    redirect_to user_path(@current_user.id)
  end

  def unsubscribe
    @event = Event.find(params[:event])
    @current_array = []
    @current_array << current_user
    @event.attendees -= @current_array
    flash[:success] = "Tu as bien quitté l'évènement !!"
    redirect_to user_path(@current_user.id)
  end

  private

  def params_event
    params.require(:event).permit(:description, :date, :place)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if User.ids.include?(params[:session][:id])
     user = User.find(params[:session][:id])
      if user
        log_in user
        redirect_to user
      end
    else
      flash.now[:danger] = "ID inconnue"
      render 'new'
    end

  end

  def destroy
   log_out
   redirect_to root_url
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params_user)
    if @user.save
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = "Couldn't save."
      render action: "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = Event.where(creator_id: @user.id)
    @current_user = @user
    @events = Event.all
    events_aging(@events)
    @upcoming = @user.attending_events & @upcoming
    @past = @user.attending_events & @past
  end

  private
  def params_user
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def events_aging(events)
    @upcoming = []
    @past = []
    events.each do |event|
        if event.date > Time.now
          @upcoming << event
        else
          @past << event
        end
    end
    @upcoming
    @past
  end

  def attending?
    @attending = []
    current_user.attending_events.each do |event|
      if event.date > Time.now
        @attending << event
      end
    end


  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Index des events</h1>

<div class="container">
  <h4>Upcoming events !!</h4>
    <% @upcoming.each_with_index do |event, i| %>
      <div class="form-group border border-info">
        <p><%= event.description %></p>
        <p><%= event.date %></p>
        <p><%= event.place %></p>
        <%= link_to "Plus d'infos", event_path(event.id), class: "btn btn-outline-info" %>
        <%= if !(@attending_list.include?(event)) then link_to "Subscribe !", {:action => :subscribe, :event => event}, :method => :put, class: "btn btn-outline-success" end %>
      </div>
    <% end %>
</div>


<div class="container">
  <h4>Past...</h4>
    <% @past.each_with_index do |event, i| %>
      <div class="form-group border border-muted">
        <p><%= event.description %></p>
        <p><%= event.date %></p>
        <p><%= event.place %></p>
        <%= link_to "Plus d'infos", event_path(event.id), class: "btn btn-outline-secondary" %>
      </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Events#new</h1>

<%= form_for @event, url: {action: "create"} do |u| %>
<div class="form-group">
    <%= u.label "Description de l'event :" %><br>
    <%= u.text_area :description %><br>
</div>
<div class="form-group">
    <%= u.label "Date :" %><br>
    <%= u.date_field :date, class: "form-control" %><br>
</div>
<div class="form-group">
    <%= u.label "Lieu :" %><br>
    <%= u.text_field :place %><br>
</div>
<div class="form-group">
    <button type=submit class="btn btn-primary">Créer le nouvel event !</button>
</div>

<% end %>

app/views/events/show.html.erb
<h3>Infos de l'évènement n° <%= @event.id %></h3>

<div class="form-group border">
<p>Créé par <%= @event.creator.name %></p>
<p><%= @event.description %></p>
<p>Date de l'évènement : <%= @event.date %></p>
<p>Rendez-vous : <%= @event.place %></p>
</div>

<div class="form-group border">
  <h4>Liste des participants</h4>
  <% @event.attendees.each do |att| %></p>
  <p><%= att.name %></p>
  <% end %>
</div>

<%= if !(@attending_list.include?(@event)) && @event.date > Time.now then link_to "Subscribe !", {:action => :subscribe, :event => @event}, :method => :put, class: "btn btn-outline-success" end %>

app/views/layouts/_header.html.erb
<header>
<ul class="nav  navbar justify-content-center bg-dark nav-pills">
  <li class="nav-item">
    <%= link_to "HOME", root_path, class: "nav-link navbar-brand btn btn-danger" %>
  </li>
  <% if logged_in? %>
  <li class="nav-item">
    <%= link_to "Profile", current_user, class: "nav-link navbar-brand btn btn-primary" %>
  </li>
  <li class="nav-item">
    <%= link_to "Index events", events_path, class: "nav-link navbar-brand btn btn-success" %>
  </li>
  <li class="nav-item">
    <%= link_to "Log out", logout_path, method: :delete, class: "nav-link navbar-brand btn btn-danger"%>
  </li>
  <% else %>
  <li class="nav-item">
    <%= link_to "Sign up now!", signup_path, class: "nav-link navbar-brand btn btn-success" %>
  </li>
  <% end %>
</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W5D4EventbriteLike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
<h3>Nouvel utilisateur</h3>

        <%= form_for @user, url: {action: "create"} do |u| %>
        <div class="form-group">
            <%= u.label "Ton pseudo ici :" %><br>
            <%= u.text_field :name %><br>
        </div>
        <div class="form-group">
            <button type=submit class="btn btn-primary">Créer le nouveau User</button>
        </div>

        <% end %>

</div>

app/views/users/show.html.erb
<h4>Bienvenue <%= @user.name %></h4>
<h2>Retiens bien ton ID pour te login plus tard : <strong><%= @user.id %></strong></h2>

<p>Voici les évènements que tu as créé :</p>
<% @created_events.each_with_index do |event, i| %>
  <div class="form-group border">
    <p><%= event.creator.name %></p>
    <p><%= event.description %></p>
    <p><%= event.date %></p>
    <p><%= event.place %></p>
  </div>
<% end %>

<p>Voici les évènements auquel tu participes :</p>
    <h4>Upcoming !!</h4>
<% @upcoming.each_with_index do |event, i| %>
  <div class="form-group border">
    <p><%= event.creator.name %></p>
    <p><%= event.description %></p>
    <p><%= event.date %></p>
    <p><%= event.place %></p>
      <%= link_to "Unsubscribe", {:controller => :events, :action => :unsubscribe, :event => event.id}, :method => :put, class: "btn btn-outline-danger" %>
  </div>
<% end %>

    <h4>Past...</h4>
<% @past.each_with_index do |event, i| %>
  <div class="form-group border">
    <p><%= event.creator.name %></p>
    <p><%= event.description %></p>
    <p><%= event.date %></p>
    <p><%= event.place %></p>
  </div>
<% end %>

<%= link_to "Créer un évènement", new_event_path, class: "btn btn-warning" %>